version: '3'

services:
  db:
    image: postgres:12.3
    volumes:
      - postgres-data:/data/db
    restart: always
    container_name: oclapi2_db
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_HOST_AUTH_METHOD=trust
  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    healthcheck:
      test: "exit 0"
  api:
    build: .
    container_name: oclapi2
    restart: always
    volumes:
      - .:/code
    command: sh -c ./startup.sh
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      - REDIS_HOST=redis
      - DB_HOST=db
      - ENV=dev
      - SECRET_KEY
      - SENTRY_DSN_KEY
      - EMAIL_HOST_PASSWORD
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_STORAGE_BUCKET_NAME
  celery:
    build: .
    container_name: celery
    command: sh -c ./start_celery_worker.sh
    links:
      - db
      - redis
    restart: always
    volumes:
      - .:/code
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - DB_HOST=db
      - ENV=dev
  flower:
    build: .
    container_name: flower
    command: sh -c ./start_flower.sh
    volumes:
      - .:/code
    ports:
      - "5555:5555"
    depends_on:
      - celery
    links:
      - redis
    environment:
      - C_FORCE_ROOT=1
      - SECRET_KEY
    restart: always
    healthcheck:
      test: "exit 0"
volumes:
  postgres-data:
